version: '3.7'

services:
  db:
    image: postgres:13.3
    container_name: test_task_pg
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build:
      context: .
    container_name: chat_bot_app
    command: ['/test_task_for_galiullin/docker/app.sh']
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./chat_bot:/test_task_for_galiullin/chat_bot


